project:
  type: website

website:
  title: "DSAN-5000: Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/about/about.qmd
        text: About Me
      - href: pages/code/code.qmd
        text: Code
      - href: pages/data/data.qmd
        text: Data
      - href: pages/introduction/introduction.qmd
        text: Introduction
      - href: pages/datagathering/datagathering.qmd
        text: Data Gathering
      - href: pages/datacleaning/datacleaning.qmd
        text: Data Cleaning
      - href: pages/eda/eda.ipynb
        text: Data Exploration
      - href: pages/clustering/clustering.ipynb
        text: Clustering
      - href: pages/dimred/dimred.ipynb
        text: Dimensionality Reduction
      - href: pages/dectree/dectree.ipynb
        text: Decision Trees
      - href: pages/naivebayes/naivebayes.qmd
        text: Naive Bayes
      - href: pages/conclusions/conclusions.qmd
        text: Conclusions

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    code-overflow: wrap
    self-contained: true
    embed-resources: true
editor: 
  markdown: 
    wrap: 65
knitr:
  opts_chunk: 
    collapse: false
    comment: "#>"
    fig.path: "figures/"
    fig.align: "center"
    dev: "png"
    echo: true
    message: false
    warning: true
    tidy: false
    tidy.opts: 
      blank: false
      width.cutoff: 60
      wrap: 60