# Conclusions

The intention of this project was to elucidate the underlying factors that are essential to a country's freedom. The project sought to answer the question, how can we best measure freedom? Data was extracted from the Cato Institute's Human Freedom Index, the International Monetary Fund's World Economic Outlook Dataset, and News articles from the BBC. The news articles were selected based on their mention of the most and least free countries in the world according to the Human Freedom Index - Switzzerland and Syria, respectively. The data was consolidated and preprocessed for several analyses. This cleaning involved merging the datasets, susbetting for the appropriate time (2019-2020), typecasting the data appropriately, and replacing NAs selectively dependent on the analyses. \newline

Following data extraction and cleaning, exploratory data anaylsis was conducted. Generally, the two response variables in this analysis were political regime (categorical) and human freedom score (continous). These dependent variables were selected in order to analyze the relationships between freedom and a variety of economic, political, safety, and human rights related factors. The EDA included univariate graphical summaries, univariate numeric summaries, bivariate graphical summaries, and bivarate numeric summaries. The EDA revealed that several features such as education level, economic freedom, and regime are associated with human freedom. From here, the hypotheses were refined to focus on these factors as they relate to both human freedom and political regime. \newline

Next, Clusltering analyses were conducted in order to further evaluate these relationships. The question of interest in this analyses was, do the features of the dataset adequately predict political regime? Three different clustering methods were implemented: K-means clustering, Density- Based Spatial Clsutering of Applicatoins with Noise (DBSCAN), and Heirarchical Clustering. The conclusion of this analysis is that the clusters are somewhat poorly definied independent of the clustering method implemented. DBSCAN performed the best, although the cluster noise remained high. Outlying countries with extreme features might have interfered with the purity of each cluster, or it is possible that the features were just similar across the political regimes. \newline

The next analysis conducted was Dimensionality Reduction. Again, dimensionality reduction was conducted with respect to political regime. This was done to determine if the reduced information form the dataset in two dimensions demonstrates stratificiation between political regimes. Both Principal Component Analysis (PCA) and t-distributed Stochastic Neighbor Embedding (t-SNE) were used as dimensionality reduction techniques. The PCA resulted in soemwhat defined clusters, with one cluster containing the most number of points. There was slight stratification based on political regime. The t-SNE had similar results, but the clusters of political regimes were more defined. This was particularly apparent at a perplexity of 30. These analyses demonstrated that the poltical regimes differ based on economic, poolitical, and human freedom factors. \newline

Decision tree and Random Forest algorithms were then implemented on the dataset for classification and regression, respectively. These analyses sought to evaluate the two response variables of interest in this study - political regime and human freedom score. A decision tree was constructed for classification of political regime, which performed well with an an accuracy of 92%. A random forest was built for the same task, with an accruacy of 88%. These classifiers demonstrated that a rule based system can be used to predict political regime based on the economic, political, social, and human freedom factors of interest. Next, a decision tree was built for regression of the data on human freedom score. The random forest had a coefficient of determination of 0.97, indicating strong performance. The random forest constructed for the same task also produced an accuracy of 0.97. These models indicated that a rule bsaed system can be used to predict human freedom score based on the economic, political, social, and human freedom factors of interest. 

Finally, Naive Bayesian machine learning was used to classify the text data from the BBC articles and the political regime of countries based on the features of the dataset. The classification was innefective for the text data due the the high number of stop words in the articles. The algorithm was also used for the classification of political regime. However, the classifier performed poorly with an overall accuracy of 59.3%. The misclassification happened at the close points on the continuum. That is, closed versus electoral autocracies were often misclassified. But, closed autocracy was not misclassified with liberal democracy, for example. This algorithm was not optimal for differentiaing between the four types of political regime as described in this dataset. 

Overall, several models were developed to predict the political regime of a country, and the countries human freedom score. The models were generally well performing, although some techniques, such as decision trees, were more effective than others, such as naive bayes algoirithms. Practically, this analysis determined that the economic, social, political, and freedom factors included in the dataset are predictors of both political regime and human freedom score. These models are useful to predicting future changes in freedom of regime. This is an undoubtedly important conclusion as the political dynamics of our world are constantly changing. Human freedom remains of the utmost important to every individual on the globe. Being able to predict freedom under different regimes and systems is important to udnerstanding how we can best preserve and promote human freedom on a global scale. It is important to note, however, that these systems are highly complex and further research is imperative to model and understand how freedom ought to be measured and maximized in any given country. Some weaknesses of note are cultural differences and data integrity. Cultural differences between nations are somewhat intangible, and conseuqnently difficult to measure and include in this analysis. However, it is likely important to the degree of freedom in the country. Data integrity is also an issue, as some countries such as North Korea might have very unreliable data regarding the economy or freedom of individuals. In short, this analysis demonstrated the ability to predict political regime and human freedom based on several diverse metrics of any given nation. This is important to understanding the freedom of the individual in different contexts worldwide.
